version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription-platform
    working_dir: /var/www
    volumes:
      - ./subscription-platform:/var/www
    ports:
      - "8000:8000"
    environment:
      - WWWUSER=1000
      - WWWGROUP=1000
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0
    container_name: subscription-platform-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  mysql_data:
